### ISSUE TITLE
Travel_history (Priority = Medium)

### ISSUE THREAD

**Issue by sadiekelly** [globaldothealth/outbreak-schema#8]
*Minimum EpiCore variable = Travelled outside since xx weeks/months prior to symptom onset

The day0 schema collects data on any travel history, whereas the T0 toolkit and EpiCore variable defines a time period for travel history.

Should a time period be added to the day0 schema? Is this available from G.h sources?

**Comment by lauramerson** [comment]
A time period makes the information relevant at collection. It is not critical that the time periods align (i.e., if one says 2 weeks and one says 3 weeks, it is not important, especially since different diseases have different incubation periods). I'd suggest the day0 schema is correct to collect any relevant travel history, without specific time period, as relevant times may change and you want to capture the recording of any period felt relevant by the public health agency at the time.

**Comment by sadiekelly** [comment]
No changes required, keep the day0 schema flexible to capture data over any relevant time period
